flash-cards-develop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'

  root 'static_pages#home'

  get 'standard_game_mode/index'
  post 'standard_game_mode/next_card'
  post 'standard_game_mode/start'

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'

  get 'categories' => 'categories#index'
  get 'category' => 'categories#show'

  get 'collections/my_filter'
  resources :collections do
    resources :cards
    resources :reviews
  end
end

flash-cards-develop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

flash-cards-develop/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :collection
  validates :front, :back, presence: true
  validates :front, uniqueness: true
end

flash-cards-develop/app/models/category.rb
class Category < ApplicationRecord
  has_many :collections
end

flash-cards-develop/app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category
  has_many :cards, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likers, through: :reviews, source: :user
end

flash-cards-develop/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :collection
  belongs_to :user
end

flash-cards-develop/app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
end

flash-cards-develop/app/models/user.rb
class User < ApplicationRecord
  has_many :collections
  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :scores, dependent: :destroy
end

flash-cards-develop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_breadcrumbs

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: %i[password password_confirmation current_password name phone]
    )
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username admin])
  end

  def set_breadcrumbs
    @breadcrumbs = []
  end
  
  def add_breadcrumb(label, path = nil)
    @breadcrumbs << {
      label: label,
      path: path
    }
  end
  

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referer || root_path)
  end
end

flash-cards-develop/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_collection
  before_action :set_card, only: %w[show edit update destroy]

  def show; end

  def new
    @card = @collection.cards.build
  end

  def create
    @card = @collection.cards.build(card_params)
    respond_to do |format|
      if @card.save
        format.html { redirect_to @collection, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @collection, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to collection_path(@collection), notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

  def set_card
    @card = @collection.cards.find(params[:id])
  end

  def card_params
    params.require(:card)
          .permit(:front, :back, :image_file_name, :category)
  end
end

flash-cards-develop/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

flash-cards-develop/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_collection
  

  def create
    @review = @collection.reviews.build(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to collection_path(@collection)
    end
  end

  private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

  def review_params
    params.require(:review).permit(:rate)
  end
end

flash-cards-develop/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_current_user, except: [:index]

  def index
    @users = User.all
  end

  def show
    add_breadcrumb('User')
  end

  def edit
    add_breadcrumb('User', users_show_path)
    add_breadcrumb('Edit')
  end
  

  # private

  # def set_current_user
  #   @user = current_user
  # end
end

flash-cards-develop/app/helpers/application_helper.rb
module ApplicationHelper
end

flash-cards-develop/app/helpers/cards_helper.rb
module CardsHelper
end

flash-cards-develop/app/helpers/categories_helper.rb
module CategoriesHelper
end

flash-cards-develop/app/helpers/collections_helper.rb
module CollectionsHelper
end

flash-cards-develop/app/helpers/reviews_helper.rb
module ReviewsHelper
end

flash-cards-develop/app/helpers/standard_game_mode_helper.rb
module StandardGameModeHelper
end

flash-cards-develop/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

flash-cards-develop/app/helpers/users_helper.rb
module UsersHelper
end

flash-cards-develop/app/views/layouts/_breadcrumbs.html.erb
<% if controller_name != 'static_pages' %>
<nav aria-label="breadcrumb", class='mb-n3'>
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href='/'>Home</a></li>
    <% @breadcrumbs.each do |breadcrumb| %>
      <% if breadcrumb[:path].nil? %>
        <li class="breadcrumb-item active" aria-current="page"><%= breadcrumb[:label] %></li>
      <% else %>
        <li class="breadcrumb-item">
          <%= link_to breadcrumb[:label], breadcrumb[:path] %>
        </li>
      <% end %>
    <% end %>
  </ol>
  
</nav>
<% end %>

flash-cards-develop/app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start sticky-bottom bg-dark" style="color: #fff;">

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    Copyright © 2021 FlashCards.  All rights reserved.
  </div>
</footer>

flash-cards-develop/app/views/layouts/_header.html.erb
  <%# <div class="shadow-lg p-3 mb-5 bg-white rounded">Larger shadow</div> %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-lg">
  <div class="container-fluid">
    <div class="container-fluid">
    <%= link_to image_tag('logo.svg'), root_path, class: "navbar-brand" %>
    <%= link_to 'FlashCards', root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Collections', collections_path, class: "nav-link active" %>
        <%= link_to 'About', about_path, class: "nav-link" %>
      </div>
      <div class="navbar-nav ml-auto">
      <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-1" href="#" id="navbarDarkDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, collections_my_filter_path({category_id: category.id}), class: 'dropdown-item' %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      </div>
      <% if current_user %>
        <%= link_to 'Profile', user_path(current_user), class: "btn btn-outline-light" %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light mx-2" %>
      <% else %>
        <%= link_to 'Log in', new_user_session_path, class: "btn btn-outline-light" %>
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-light mx-2" %>
      <% end %>
      </div>
    </div>
  </div>
</nav>

flash-cards-develop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashCards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' rel='stylesheet'>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= render 'layouts/breadcrumbs' %>

    <% if notice %>
      <div aria-live="polite" aria-atomic="true" class="position-relative" >
        <div class="toast-container position-absolute p-3" style="width: 300px; top: 0; left: 0;">
          <div class="toast" data-delay="3000">
            <div class="toast-header">
              <strong class="mr-auto text-primary">Notification</strong>
              <small class="text-muted">Just now</small>
              <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
            </div>
            <div class="toast-body">
              <%= notice %>
            </div>
          </div>
        </div>
      </div>

      <!-- Popper.js first, then Bootstrap JS -->
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"></script>
      <%= javascript_pack_tag 'toast' %>
    <% end %>

    <% if alert %>
      <p class='alert'><%= alert %></p>
    <% end %>

    <div class = 'content'>
      <%= yield %>
    </div>

    <% if false %>
      <%= render 'layouts/footer' %>
    <% end %>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>