flash-cards-develop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'

  root 'static_pages#home'

  get 'standard_game_mode/index'
  post 'standard_game_mode/next_card'
  post 'standard_game_mode/start'

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'

  get 'categories' => 'categories#index'
  get 'category' => 'categories#show'

  get 'collections/my_filter'
  resources :collections do
    resources :cards
    resources :reviews
  end
end

flash-cards-develop/app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category
  has_many :cards, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likers, through: :reviews, source: :user
end

flash-cards-develop/app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :require_correct_user, only: %i[edit update destroy]
  before_action :set_collection, only: %i[show edit update destroy]

  def index
    @collections = Collection.all
    add_breadcrumb('Collections')
  end

  def my_filter
    category = Category.find(params[:category_id])
    @collections = category.collections
    add_breadcrumb('Collections', collections_path)
    add_breadcrumb("#{category.name} category" )
    render template: 'collections/index', locals: {collections: @collections}
  end

  def show
    @cards = @collection.cards
    @average_rate = @collection.reviews.empty? ? 0 : @collection.reviews.average(:rate)
    @user_review = current_user.reviews.find { |review| review.collection_id == @collection.id }
    category = Category.find(@collection.category_id)
    add_breadcrumb('Collections', collections_path)
    add_breadcrumb("#{category.name} category", collections_my_filter_path({category_id: category.id}) )
    add_breadcrumb(@collection.title)
  end

  def new
    @collection = current_user.collections.build
    add_breadcrumb('Collections', collections_path)
    add_breadcrumb('New')
  end

  def create
    @collection = current_user.collections.build(collection_params)
    if @collection.save
      redirect_to @collection
    else
      render :new
    end
  end

  def edit
    add_breadcrumb('Collections', collections_path)
    add_breadcrumb(@collection.title, collection_path(@collection))
    add_breadcrumb('Edit')
  end

  def update
    if @collection.update(collection_params)
      redirect_to @collection
    else
      render :edit
    end
  end

  def destroy
    @collection.destroy
    redirect_to collections_path
  end

  private

  def require_correct_user
    redirect_to @collection unless current_user
  end

  def set_collection
    @collection = Collection.find(params[:id])
  end

  def collection_params
    params.require(:collection)
          .permit(:title, :description)
  end
end

flash-cards-develop/app/helpers/collections_helper.rb
module CollectionsHelper
end

flash-cards-develop/app/views/collections/_collection.html.erb
<% collections.each do |collection| %>
  <div class="col">
    <div class="card my-3 shadow rounded">
      <div class="card-body">
        <div class='d-flex'>
          <h5 class="card-title"><%= collection.title %></h5>
          <p class='ml-auto'>(<%= pluralize(collection.cards.count, 'card') %>)</p>
        </div>
        <p class="card-text"><%= collection.description %></p>
        <% if current_user %>
          <%= link_to 'View', collection, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

flash-cards-develop/app/views/collections/_form.html.erb
<%= form_with(model: @collection, local: true) do |f| %>

  <%= f.label :title%>
  <%= f.text_field :title%>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit "Submit" %>

<% end %> 

flash-cards-develop/app/views/collections/_stars.html.erb
<div class='rating mt-3 ml-5'>
  <input type='radio' name='star' id='star1'><label for='star1'></label>
  <input type='radio' name='star' id='star2'><label for='star2'></label>
  <input type='radio' name='star' id='star3'><label for='star3'></label>
  <input type='radio' name='star' id='star4'><label for='star4'></label>
  <input type='radio' name='star' id='star5'><label for='star5'></label>
</div>

flash-cards-develop/app/views/collections/edit.html.erb
<div class='container'>

  <h1 class='my-5'>Edit collection</h1>
  <%= render 'form', collection: @collection %>

</div>
 

flash-cards-develop/app/views/collections/index.html.erb
<div class='container my-5'>
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<br>

<h1 class='text-center'>Choose card collection:</h1>
<% if !current_user %>
  <div class="alert alert-warning mx-auto", style='max-width: 600px;'>
   You need to sing up or log in to have access to the cards!
  </div>
<% end %>
<% if params[:category_id] %>
  <h4 class='text-center'>Category: <%= Category.find(params[:category_id]).name %></h4>
<% else %>
  <h4 class='text-center'>(all categories)</h4>
<% end %>
<div class="container">

<div class="row row-cols-1 row-cols-md-2 g-4 my-3">
  <%= render 'collection', collections: @collections %>
</div>
</div>

<% if current_user %>
<div class='d-flex justify-content-center'>
  <%= link_to 'Add new collection', new_collection_path, class: 'btn btn-primary'%>
</div>
<% end %>

</div>
</div>

flash-cards-develop/app/views/collections/new.html.erb
<div class='container'>

  <h1 class='my-5'>New collection</h1>
  <%= render 'form', collection: @collection %>

</div>

flash-cards-develop/app/views/collections/show.html.erb
<div class='container my-5'>
<h1 class='text-center my-3'><%= @collection.title %></h1>

<h3>Description</h3>
<p><%= @collection.description %></p>

<% if @average_rate.zero? %>
  <h5>No reviews yet!</h5>
<% else %>
  <div id='avg-rate' data-score='<%= @average_rate %>'>
  <label><strong>Average Rate:</strong></label>
  </div>
  <p>(based on <%= pluralize @collection.reviews.count, 'review' %>)</p>
<% end %>

<% if @collection.likers.include? current_user %>
  <div id='user-rate' data-score='<%= @user_review.rate %>'>
    <label><strong>Your rate: </strong></label>
  </div>
<% else%>
  <%= render 'reviews/form', collection: @collection, review: @collection.reviews.build %>
<% end %>

<div class='d-flex justify-content-center'>
  <%= link_to 'Play with cards', standard_game_mode_index_path({collection_id: @collection.id}), class: 'btn btn-success' %>
</div>

<h3 class='text-center my-3'>Cards</h3>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Card</th>
      <th scope="col">Back</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% num = 1 %>
  <% @cards.each do |card| %>
  <tr>
    <th scope="row"><%= num %></th>
    <% if @collection.user_id == current_user.id %>
      <td><%= link_to card.front, collection_card_path(@collection, card) %></td>
      <td><%= card.back %></td>
      <td><%= link_to 'Edit card', edit_collection_card_path(@collection, card), class: 'btn btn-outline-primary text-nowrap mx-2'%></td>
      <td><%= link_to 'Remove card', collection_card_path(@collection, card), method: :delete, class: 'btn btn-danger text-nowrap mx-2'%></td>
    <% else %>
      <td><%= card.front %></td>
      <td><%= card.back %></td>
      <td></td>
      <td></td>
    <% end %>
    <% num += 1 %>
  </tr>
  <% end %>
  </tbody>
</table> 

<% if @collection.user_id == current_user.id %>
<div class='d-flex justify-content-center'>
  <%= link_to 'Add new card', new_collection_card_path(@collection), class: 'btn btn-primary mx-2 my-2'%>
  <%= link_to 'Delete collection', @collection, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger my-2' %>
</div>
<% end %>
</div>

<script>
  $('#avg-rate').raty({
  readOnly: true,
  half: true,
  score: function() {
    return $(this).attr('data-score');
  },
  hints: false,
  space: true,
  path: '/assets/',
});
</script>

<script>
  $('#user-rate').raty({
  readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  },
  hints: false,
  space: true,
  path: '/assets/',
});
</script>