flash-cards-develop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'

  root 'static_pages#home'

  get 'standard_game_mode/index'
  post 'standard_game_mode/next_card'
  post 'standard_game_mode/start'

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'

  get 'categories' => 'categories#index'
  get 'category' => 'categories#show'

  get 'collections/my_filter'
  resources :collections do
    resources :cards
    resources :reviews
  end
end

flash-cards-develop/app/controllers/standard_game_mode_controller.rb
class StandardGameModeController < ApplicationController
  before_action :authenticate_user!
  before_action :set_collection

  def index
    @card = @collection.cards.first
  end

  def start
    @current_card = @collection.cards.first
    @offset = 1

    score = current_user.scores.build(collection_id: @collection.id)
    if score.save!
      @game_id = score.id
    else
      # TODO: should be logger and redirect
      puts "************************** Score wasn't saved"
    end
  end

  def next_card
    # if card was skipped - add it's id to database
    if params[:skipped_card]
      score = Score.find(params[:game_id])
      score.skipped_cards.push(params[:skipped_card].to_i)
      score.save!
    end

    # check if we still have cards
    if params[:offset].to_i < @collection.cards.count
      @current_card = @collection.cards.offset(params[:offset]).first

      @offset = params[:offset].to_i + 1
      @game_id = params[:game_id]
    else
      score = Score.find(params[:game_id])
      score.spent_time = (Time.now - score.created_at).to_i
      score.status = 'finished'
      score.save!

      @totall_cards_amount = @collection.cards.count
      @skipped_cards_amount = Score.find(params[:game_id]).skipped_cards.size
      # @spent_time = Time.at(score.spent_time).utc.strftime("%M:%S")
    end

    respond_to do |format|
      format.js
    end
  end

  private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end
end

flash-cards-develop/app/helpers/standard_game_mode_helper.rb
module StandardGameModeHelper
end

flash-cards-develop/app/views/standard_game_mode/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<br>

<div class="container">
  <div class="row justify-content-md-center text-center">
  <span>
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-stopwatch" viewBox="0 0 16 16">
      <path d="M8.5 5.6a.5.5 0 1 0-1 0v2.9h-3a.5.5 0 0 0 0 1H8a.5.5 0 0 0 .5-.5V5.6z"/>
      <path d="M6.5 1A.5.5 0 0 1 7 .5h2a.5.5 0 0 1 0 1v.57c1.36.196 2.594.78 3.584 1.64a.715.715 0 0 1 .012-.013l.354-.354-.354-.353a.5.5 0 0 1 .707-.708l1.414 1.415a.5.5 0 1 1-.707.707l-.353-.354-.354.354a.512.512 0 0 1-.013.012A7 7 0 1 1 7 2.071V1.5a.5.5 0 0 1-.5-.5zM8 3a6 6 0 1 0 .001 12A6 6 0 0 0 8 3z"/>
    </svg>
    <h2 id="stopwatch" style="margin-bottom: 0;"><time>00:00</time></h2>
  </span>
  </div>
</div>

<%= render 'cards/card', card: @card %>

<div class="container" id="buttons-container">
  <div class="row justify-content-md-center text-center">
    <div class="col col-sm-2">
      <%= button_to "Start",
          standard_game_mode_start_path({ collection_id: @collection.id }),
          remote: true,
          method: :post,
          form: { id: "start-game-button" },
          class: "btn btn-warning btn-lg btn-block" %>
    </div>
  </div>
  <div class="row justify-content-md-center text-center">
    <div class="col col-sm-2">
      <%= button_to "I don't know",
          standard_game_mode_next_card_path(),
          remote: true,
          method: :post,
          form: { id: "skip-card-button" },
          class: "btn btn-danger btn-lg btn-block" %>
    </div>
    <div class="col col-sm-2">
      <%= button_to "I know",
          standard_game_mode_next_card_path(),
          remote: true,
          method: :post,
          form: { id: "next-card-button" },
          class: "btn btn-success btn-lg btn-block" %>
    </div>
  </div>
  <div class="row justify-content-md-center text-center" hidden="true">
    <div class="col col-sm-2">
      <%= link_to 'Retry', standard_game_mode_index_path({ collection_id: @collection.id }), class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  </div>
</div>

<script>
  document.addEventListener("turbolinks:load", function() {
    const cardContainer = document.getElementById('card-container');
    cardContainer.style.filter = "blur(5px)";

    const skipButton = document.getElementById("skip-card-button");
    skipButton.style.display = "none"

    const nextButton = document.getElementById("next-card-button");
    nextButton.style.display = "none"
  })
</script>

<%= javascript_pack_tag 'stopwatch' %>

flash-cards-develop/app/views/standard_game_mode/next_card.js.erb
function checkCardState() {
  const card = document.getElementById("card");
  if (card.classList.contains('flipped')) {
    card.classList.remove('flipped');
    window.setTimeout(changeCard, 200);
  } else {
    changeCard();
  }
}

function stopTimerAndRemoveButtons() {
    clearTimeout(window.t);

    document.getElementsByClassName("col")[1].parentNode.remove();
}

function changeCard() {
  <% if @current_card %>
    const front = document.getElementById("front");
    front.innerHTML = "<%= @current_card.front %>";

    const back = document.getElementById("back");
    back.innerHTML = "<%= @current_card.back %>";

    const skipButton = document.getElementById("skip-card-button");
    skipButton.action = "<%= raw(standard_game_mode_next_card_url({ collection_id: @collection.id, offset: @offset, game_id: @game_id, skipped_card: @current_card.id })) %>";

    const nextButton = document.getElementById("next-card-button");
    nextButton.action = "<%= raw(standard_game_mode_next_card_url({ collection_id: @collection.id, offset: @offset, game_id: @game_id, skipped_card: nil  })) %>";
  <% else %>
    stopTimerAndRemoveButtons();

    const totallCardsAmount = <%= @totall_cards_amount %>;
    const skippedCardsAmount = <%= @skipped_cards_amount %>;
    let message = `Your score: ${totallCardsAmount - skippedCardsAmount}/${totallCardsAmount}\n`;
    message += `Elapsed time: ${document.getElementById('stopwatch').textContent}`;
    alert(message);

    document.getElementsByClassName("col")[0].parentNode.hidden = false
  <% end %>
}

checkCardState();

flash-cards-develop/app/views/standard_game_mode/start.js.erb
function startGame() {
  document.getElementsByClassName("col")[0].parentNode.remove();

  const skipButton = document.getElementById("skip-card-button");
  skipButton.action = "<%= raw(standard_game_mode_next_card_url({ collection_id: @collection.id, offset: @offset, game_id: @game_id, skipped_card: @current_card.id })) %>"
  skipButton.style.display = "block"

  const nextButton = document.getElementById("next-card-button");
  nextButton.action = "<%= raw(standard_game_mode_next_card_url({ collection_id: @collection.id, offset: @offset, game_id: @game_id, skipped_card: nil })) %>";
  nextButton.style.display = "block"

  const cardContainer = document.getElementById('card-container');
  cardContainer.style.removeProperty("filter");
}

startGame();

window.onbeforeunload = function() {
  return 'Are you sure you want to leave?';
};