flash-cards-develop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'

  root 'static_pages#home'

  get 'standard_game_mode/index'
  post 'standard_game_mode/next_card'
  post 'standard_game_mode/start'

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'

  get 'categories' => 'categories#index'
  get 'category' => 'categories#show'

  get 'collections/my_filter'
  resources :collections do
    resources :cards
    resources :reviews
  end
end

flash-cards-develop/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :collection
  validates :front, :back, presence: true
  validates :front, uniqueness: true
end

flash-cards-develop/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_collection
  before_action :set_card, only: %w[show edit update destroy]

  def show; end

  def new
    @card = @collection.cards.build
  end

  def create
    @card = @collection.cards.build(card_params)
    respond_to do |format|
      if @card.save
        format.html { redirect_to @collection, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @collection, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to collection_path(@collection), notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

  def set_card
    @card = @collection.cards.find(params[:id])
  end

  def card_params
    params.require(:card)
          .permit(:front, :back, :image_file_name, :category)
  end
end

flash-cards-develop/app/helpers/cards_helper.rb
module CardsHelper
end

flash-cards-develop/app/views/cards/_card.html.erb
<div class="container" id="card-container">
  <div class="row justify-content-md-center">
    <div class="card text-center flipCard" style="width: 18rem; height: 20rem; border: 10px solid transparent;">
      <div class="card" id="card" onclick="this.classList.toggle('flipped');">
        <h2 class="side front" id="front"><%= card.front %></h2>
        <p class="side back" id="back"><%= card.back %></p>
      </div>
    </div>
  </div>
</div>

flash-cards-develop/app/views/cards/_form.html.erb
<%= form_with(model: [collection, card], local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :front %>
    <%= form.text_field :front %>
  </div>

  <div class="field">
    <%= form.label :back %>
    <%= form.text_field :back %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

flash-cards-develop/app/views/cards/edit.html.erb
<div class='container'>
<h1>Editing Card</h1>

<%= render 'form', collection: @collection, card: @card %>

<%= link_to 'Cancel', @collection, class: 'btn btn-secondary' %> 
</div>

flash-cards-develop/app/views/cards/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<br>

<h1 style="text-align: center;">Choose category:</h1>

<div class="container">
  <% @categories.each_slice(2) do |three_categories| %>
    <div class="row">
      <% three_categories.each do |category| %>
        <div class="col-sm">
          <div class="flipCard">
            <a href=<%= standard_game_mode_index_path({ category: category }) %>>
              <div class="card">
                <div class="side front" style="background-color: <%= @colors_enumerator.next %>">
                  <%= category %>
                </div>
              </div>
            </a>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="container" id="searchDiv">
  <input type="text" id="myInput" placeholder="Search for cards.." />
  <table class="table caption-top" id="myTable">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Front</th>
        <th scope="col">Back</th>
        <th scope="col">Category</th>
      </tr>
    </thead>
    <tbody>
      <% @cards.each do |card| %>
        <tr>
          <th scope="row">
            <a href=<%= card_path(card) %>><%= card.id %></a>
          </th>
          <td><%= card.front %></td>
          <td><%= card.back %></td>
          <td><%= card.category %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= javascript_pack_tag 'card' %>
<% if false %>
  <%# add jsx (React) file to view  %>
  <%= javascript_pack_tag("search_cart") %>
<% end %>

flash-cards-develop/app/views/cards/new.html.erb
<div class='container'>
<h1>New Card</h1>

<%= render 'form', collection: @collection, card: @card %>

<%= link_to 'Back', @collection, class: 'btn btn-secondary' %>
</div>

flash-cards-develop/app/views/cards/show.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<%= render 'card', card: @card %>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto">
      <%= button_to "New", new_collection_card_path, method: :get, class: "btn btn-primary" %>
    </div>
    <div class="col-md-auto">
      <%= button_to "Edit", edit_collection_card_path(@collection, @card), method: :get, class: "btn btn-warning" %>
    </div>
    <div class="col-md-auto">
      <%= button_to "Destroy",
              collection_card_path(@collection, @card),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: "btn btn-danger" %>
    </div>
  </div>
</div>